### PR TITLE
Vendor eigen, tweak docs

### PR DESCRIPTION
**Pull request by olilarkin**
Vendor eigen to make it a bit simpler to compile on macOS. Also a couple of docs fixes

### CODE REVIEW

**Comment by sevagh** [comment]
Thanks for the contribution! Give me a few days to test it out locally.

**Comment by sevagh** [comment]
Good news is the demixing performance is unaffected by the updated Eigen (not that I expected it to break, but still).

**Comment by olilarkin** [comment]
Hey. Indeed i had only tried the native build, not wasm. I pushed a couple of fixes which allow me to build both on macOS now.

**Comment by sevagh** [comment]
Hmm, I'd rather not remove the flag for everybody but only for macOS users via some kind of flag. What sort of machine do you have? Why does macOS not support `-march=native`? Is it a clang issue? Can you describe the processor, clang or compiler version, etc.?

There may be a CMake way of tackling this e.g.:
```
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -mfma -ffast-math -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-unsafe-math-optimizations -fno-trapping-math -fno-math-errno")

# set -march=native for non-macos
if(not ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -march=native")
endif()
```

**Comment by sevagh** [comment]
The code changed a lot since then, but thanks again for the contribution! I did end up vendoring Eigen myself and mentioning you in the commit message; hope that level of attribution is enough: https://github.com/sevagh/free-music-demixer/commit/e1eab8aaa77c98d8c54c09054672d3634687bfa4

**Pull request closed without merging**
